In [2]:
import pandas as pd

In [3]:
fname = "steam-project\data\steam_store_details_2026-03-18.csv"
steam_api = pd.read_csv(fname)
steam_api.head()

,appid,title,price_usd,price_pln,release_date,metacritic_score,languages,genre,developer,publisher,series
0,730,Counter-Strike 2,NaN,NaN,"Aug 21, 2012",NaN,"Czech, Danish, Dutch, English<strong>*</strong...","Action, Free To Play",Valve,Valve,NaN
1,1172470,Apex Legends™,NaN,NaN,"Nov 4, 2020",88.0,"English<strong>*</strong>, French<strong>*</st...","Action, Adventure, Free To Play",Respawn,Electronic Arts,NaN
2,578080,PUBG: BATTLEGROUNDS,NaN,NaN,"Dec 21, 2017",NaN,"English, Korean, Simplified Chinese, French, G...","Action, Adventure, Massively Multiplayer, Free...",PUBG Corporation,"KRAFTON, Inc.",NaN
3,1623730,Palworld,$29.99,"99,99zł","Jan 18, 2024",NaN,"English, Simplified Chinese, Traditional Chine...","Action, Adventure, Indie, RPG, Early Access",Pocketpair,Pocketpair,NaN
4,440,Team Fortress 2,NaN,NaN,"Oct 10, 2007",92.0,"English<strong>*</strong>, Danish, Dutch, Finn...","Action, Free To Play",Valve,Valve,NaN

In [4]:
steam_api.info()
steam_api.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appid             100 non-null    int64
 1   title             100 non-null    object
 2   price_usd         61 non-null     object
 3   price_pln         61 non-null     object
 4   release_date      99 non-null     object
 5   metacritic_score  53 non-null     float64
 6   languages         100 non-null    object
 7   genre             100 non-null    object
 8   developer         100 non-null    object
 9   publisher         99 non-null     object
 10  series            0 non-null      float64
dtypes: float64(2), int64(1), object(8)
memory usage: 8.7+ KB

              appid  metacritic_score  series
count  1.000000e+02         53.000000     0.0
mean   7.133389e+05         84.132075     NaN
std    7.056816e+05          7.618393     NaN
min    1.000000e+01         65.000000     NaN
25%    2.390950e+05         81.000000     NaN
50%    4.410950e+05         85.000000     NaN
75%    1.089888e+06         89.000000     NaN
max    3.241660e+06         96.000000     NaN

In [5]:
# Adding ingestion date column
import re
m = re.search(r"(\d{4}-\d{2}-\d{2})", fname)
if m:
    steam_api["ingestion_date"] = pd.to_datetime(m.group(1))

steam_api.head()

,appid,title,price_usd,price_pln,release_date,metacritic_score,languages,genre,developer,publisher,series,ingestion_date
0,730,Counter-Strike 2,NaN,NaN,"Aug 21, 2012",NaN,"Czech, Danish, Dutch, English<strong>*</strong...","Action, Free To Play",Valve,Valve,NaN,2026-03-18
1,1172470,Apex Legends™,NaN,NaN,"Nov 4, 2020",88.0,"English<strong>*</strong>, French<strong>*</st...","Action, Adventure, Free To Play",Respawn,Electronic Arts,NaN,2026-03-18
2,578080,PUBG: BATTLEGROUNDS,NaN,NaN,"Dec 21, 2017",NaN,"English, Korean, Simplified Chinese, French, G...","Action, Adventure, Massively Multiplayer, Free...",PUBG Corporation,"KRAFTON, Inc.",NaN,2026-03-18
3,1623730,Palworld,$29.99,"99,99zł","Jan 18, 2024",NaN,"English, Simplified Chinese, Traditional Chine...","Action, Adventure, Indie, RPG, Early Access",Pocketpair,Pocketpair,NaN,2026-03-18
4,440,Team Fortress 2,NaN,NaN,"Oct 10, 2007",92.0,"English<strong>*</strong>, Danish, Dutch, Finn...","Action, Free To Play",Valve,Valve,NaN,2026-03-18

In [6]:
# Droping metacritic_score column - too many missing values
steam_api.drop(columns=["metacritic_score"], inplace=True)

# Droping series column - too many missing values
steam_api.drop(columns=["series"], inplace=True)

steam_api.head()

,appid,title,price_usd,price_pln,release_date,languages,genre,developer,publisher,ingestion_date
0,730,Counter-Strike 2,NaN,NaN,"Aug 21, 2012","Czech, Danish, Dutch, English<strong>*</strong...","Action, Free To Play",Valve,Valve,2026-03-18
1,1172470,Apex Legends™,NaN,NaN,"Nov 4, 2020","English<strong>*</strong>, French<strong>*</st...","Action, Adventure, Free To Play",Respawn,Electronic Arts,2026-03-18
2,578080,PUBG: BATTLEGROUNDS,NaN,NaN,"Dec 21, 2017","English, Korean, Simplified Chinese, French, G...","Action, Adventure, Massively Multiplayer, Free...",PUBG Corporation,"KRAFTON, Inc.",2026-03-18
3,1623730,Palworld,$29.99,"99,99zł","Jan 18, 2024","English, Simplified Chinese, Traditional Chine...","Action, Adventure, Indie, RPG, Early Access",Pocketpair,Pocketpair,2026-03-18
4,440,Team Fortress 2,NaN,NaN,"Oct 10, 2007","English<strong>*</strong>, Danish, Dutch, Finn...","Action, Free To Play",Valve,Valve,2026-03-18

In [7]:
# Converting release_date to datetime, coercing errors to NaT
steam_api["release_date"] = pd.to_datetime(steam_api["release_date"], errors="coerce")

# Adding a new column to indicate if release_date is missing
steam_api["release_date_missing"] = steam_api["release_date"].isna()

steam_api.head()

,appid,title,price_usd,price_pln,release_date,languages,genre,developer,publisher,ingestion_date,release_date_missing
0,730,Counter-Strike 2,NaN,NaN,2012-08-21,"Czech, Danish, Dutch, English<strong>*</strong...","Action, Free To Play",Valve,Valve,2026-03-18,False
1,1172470,Apex Legends™,NaN,NaN,2020-11-04,"English<strong>*</strong>, French<strong>*</st...","Action, Adventure, Free To Play",Respawn,Electronic Arts,2026-03-18,False
2,578080,PUBG: BATTLEGROUNDS,NaN,NaN,2017-12-21,"English, Korean, Simplified Chinese, French, G...","Action, Adventure, Massively Multiplayer, Free...",PUBG Corporation,"KRAFTON, Inc.",2026-03-18,False
3,1623730,Palworld,$29.99,"99,99zł",2024-01-18,"English, Simplified Chinese, Traditional Chine...","Action, Adventure, Indie, RPG, Early Access",Pocketpair,Pocketpair,2026-03-18,False
4,440,Team Fortress 2,NaN,NaN,2007-10-10,"English<strong>*</strong>, Danish, Dutch, Finn...","Action, Free To Play",Valve,Valve,2026-03-18,False

In [8]:
# Removing currency symbols from price columns and converting to numeric, filling missing values with 0 (free-to-play games)
steam_api['price_usd'] = steam_api['price_usd'].astype(str).str.replace(r'[^\d\.\-]', '', regex=True)
steam_api['price_pln'] = (
    steam_api['price_pln'].astype(str)
    .str.replace(r'[^\d,\-\s\(\)]', '', regex=True)  # Remove non-numeric characters except for digits, comma, minus, parentheses, and whitespace
    .str.replace(r'\s+', '', regex=True)  # Remove any remaining whitespace
    .str.replace(',', '.', regex=True) # Replace comma with dot for decimal conversion
    .pipe(pd.to_numeric, errors='coerce')
)
steam_api["price_usd"] = pd.to_numeric(steam_api["price_usd"], errors="coerce").fillna(0)
steam_api["price_pln"] = pd.to_numeric(steam_api["price_pln"], errors="coerce").fillna(0)

steam_api.head(5)

,appid,title,price_usd,price_pln,release_date,languages,genre,developer,publisher,ingestion_date,release_date_missing
0,730,Counter-Strike 2,0.00,0.00,2012-08-21,"Czech, Danish, Dutch, English<strong>*</strong...","Action, Free To Play",Valve,Valve,2026-03-18,False
1,1172470,Apex Legends™,0.00,0.00,2020-11-04,"English<strong>*</strong>, French<strong>*</st...","Action, Adventure, Free To Play",Respawn,Electronic Arts,2026-03-18,False
2,578080,PUBG: BATTLEGROUNDS,0.00,0.00,2017-12-21,"English, Korean, Simplified Chinese, French, G...","Action, Adventure, Massively Multiplayer, Free...",PUBG Corporation,"KRAFTON, Inc.",2026-03-18,False
3,1623730,Palworld,29.99,99.99,2024-01-18,"English, Simplified Chinese, Traditional Chine...","Action, Adventure, Indie, RPG, Early Access",Pocketpair,Pocketpair,2026-03-18,False
4,440,Team Fortress 2,0.00,0.00,2007-10-10,"English<strong>*</strong>, Danish, Dutch, Finn...","Action, Free To Play",Valve,Valve,2026-03-18,False

In [11]:
# Create normalized tables

# 1. Games table - all columns except genres and languages
games = steam_api.drop(columns=['genre', 'languages']).copy()
print("Games table created:")
print(f"Shape: {games.shape}")
print(games.head())

Games table created:
Shape: (100, 9)
     appid                title  price_usd  price_pln release_date  \
0      730     Counter-Strike 2       0.00       0.00   2012-08-21
1  1172470        Apex Legends™       0.00       0.00   2020-11-04
2   578080  PUBG: BATTLEGROUNDS       0.00       0.00   2017-12-21
3  1623730             Palworld      29.99      99.99   2024-01-18
4      440      Team Fortress 2       0.00       0.00   2007-10-10

          developer        publisher ingestion_date  release_date_missing
0             Valve            Valve     2026-03-18                 False
1           Respawn  Electronic Arts     2026-03-18                 False
2  PUBG Corporation    KRAFTON, Inc.     2026-03-18                 False
3        Pocketpair       Pocketpair     2026-03-18                 False
4             Valve            Valve     2026-03-18                 False

In [15]:
# 2. Genres table - appid with individual genres (excluding "Free to Play")
genres = steam_api[['appid', 'genre']].copy()
# Split genres by comma and explode into separate rows
genres['genre'] = genres['genre'].str.split(',')
genres = genres.explode('genre')
# Strip whitespace
genres['genre'] = genres['genre'].str.strip()
# Remove "Free To Play" entries
genres = genres[genres['genre'] != 'Free To Play'].reset_index(drop=True)
print("Genres table created:")
print(f"Shape: {genres.shape}")
print(genres.head(10))

Genres table created:
Shape: (282, 2)
     appid                  genre
0      730                 Action
1  1172470                 Action
2  1172470              Adventure
3   578080                 Action
4   578080              Adventure
5   578080  Massively Multiplayer
6  1623730                 Action
7  1623730              Adventure
8  1623730                  Indie
9  1623730                    RPG

In [16]:
# 3. Languages table - appid with individual languages and audio support
languages = steam_api[['appid', 'languages']].copy()
# Split languages by comma and explode into separate rows
languages['language_raw'] = languages['languages'].str.split(',')
languages = languages.explode('language_raw')
languages = languages.drop(columns=['languages']).reset_index(drop=True)

# Check if language has audio (indicated by <strong>*</strong>)
languages['audio'] = languages['language_raw'].str.contains(r'<strong>\*</strong>', regex=True)

# Clean up language name by removing <strong>*</strong> and whitespace
languages['language'] = (
    languages['language_raw']
    .str.replace(r'<strong>\*</strong>', '', regex=True)
    .str.strip()
)

# Keep only appid, language, and audio columns
languages = languages[['appid', 'language', 'audio']]

print("Languages table created:")
print(f"Shape: {languages.shape}")
print(languages.head(15))

Languages table created:
Shape: (1361, 3)
    appid               language  audio
0     730                  Czech  False
1     730                 Danish  False
2     730                  Dutch  False
3     730                English   True
4     730                Finnish  False
5     730                 French  False
6     730                 German  False
7     730              Hungarian  False
8     730                Italian  False
9     730               Japanese  False
10    730                 Korean  False
11    730              Norwegian  False
12    730                 Polish  False
13    730  Portuguese - Portugal  False
14    730    Portuguese - Brazil  False

In [17]:
# Summary of normalized tables
print("=" * 60)
print("NORMALIZED TABLES SUMMARY")
print("=" * 60)

print(f"\n1. GAMES TABLE")
print(f"   Shape: {games.shape} (rows, columns)")
print(f"   Columns: {list(games.columns)}")
print(f"\n2. GENRES TABLE")
print(f"   Shape: {genres.shape} (rows, columns)")
print(f"   Columns: {list(genres.columns)}")
print(f"   Unique genres: {genres['genre'].nunique()}")
print(f"   Genres: {sorted(genres['genre'].unique().tolist())}")
print(f"\n3. LANGUAGES TABLE")
print(f"   Shape: {languages.shape} (rows, columns)")
print(f"   Columns: {list(languages.columns)}")
print(f"   Unique languages: {languages['language'].nunique()}")
print(f"   Languages with audio support: {languages['audio'].sum()}")
print(f"   Languages without audio support: {(~languages['audio']).sum()}")

============================================================
NORMALIZED TABLES SUMMARY
============================================================

1. GAMES TABLE
   Shape: (100, 9) (rows, columns)
   Columns: ['appid', 'title', 'price_usd', 'price_pln', 'release_date', 'developer', 'publisher', 'ingestion_date', 'release_date_missing']

2. GENRES TABLE
   Shape: (282, 2) (rows, columns)
   Columns: ['appid', 'genre']
   Unique genres: 15
   Genres: ['Action', 'Adventure', 'Animation & Modeling', 'Casual', 'Design & Illustration', 'Early Access', 'Indie', 'Massively Multiplayer', 'Photo Editing', 'RPG', 'Racing', 'Simulation', 'Sports', 'Strategy', 'Utilities']

3. LANGUAGES TABLE
   Shape: (1361, 3) (rows, columns)
   Columns: ['appid', 'language', 'audio']
   Unique languages: 62
   Languages with audio support: 444
   Languages without audio support: 917