In [28]:
import pandas as pd

fname = "steamspy_top100_games_2026-03-18.csv"
steam_spy = pd.read_csv("steam-project/data/" + fname)
steam_spy.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,NaN,7642084,1173003,0,"100,000,000 .. 200,000,000",33313,707,6299,329,0,0,0,1013936
1,1172470,Apex Legends,Respawn,Electronic Arts,NaN,668053,326926,0,"100,000,000 .. 200,000,000",10807,509,907,223,0,0,0,124262
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",NaN,1520457,1037487,0,"100,000,000 .. 200,000,000",24163,731,6086,336,0,0,0,314682
3,1623730,Palworld,Pocketpair,Pocketpair,NaN,358266,22443,0,"50,000,000 .. 100,000,000",3950,834,2217,316,2999,2999,0,18028
4,440,Team Fortress 2,Valve,Valve,NaN,1044264,117208,0,"50,000,000 .. 100,000,000",21685,334,4404,98,0,0,0,43819

In [29]:
# Sorting data by ccu in descending order
steam_spy.sort_values(by="ccu", ascending=False, inplace=True)
steam_spy.head(10)

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,NaN,7642084,1173003,0,"100,000,000 .. 200,000,000",33313,707,6299,329,0,0,0,1013936
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",NaN,1520457,1037487,0,"100,000,000 .. 200,000,000",24163,731,6086,336,0,0,0,314682
25,252490,Rust,Facepunch Studios,Facepunch Studios,NaN,1071135,156649,0,"20,000,000 .. 50,000,000",22059,1295,2988,694,3999,3999,0,143870
1,1172470,Apex Legends,Respawn,Electronic Arts,NaN,668053,326926,0,"100,000,000 .. 200,000,000",10807,509,907,223,0,0,0,124262
19,431960,Wallpaper Engine,Wallpaper Engine Team,Wallpaper Engine Team,NaN,876898,17560,0,"20,000,000 .. 50,000,000",4777,140,1012,11,499,499,0,91184
8,271590,Grand Theft Auto V Legacy,Rockstar North,Rockstar Games,NaN,1739980,250576,0,"50,000,000 .. 100,000,000",14313,833,5643,76,0,0,0,67851
5,1938090,Call of Duty: Modern Warfare II,"Treyarch, Raven Software, Beenox, High Moon St...",Activision,NaN,419594,294520,0,"50,000,000 .. 100,000,000",5153,674,677,184,3849,6999,45,67419
49,1203220,NARAKA: BLADEPOINT,24 Entertainment,NetEase Games Global,NaN,225960,98967,0,"10,000,000 .. 20,000,000",8327,599,444,295,0,0,0,66954
20,1086940,Baldur's Gate 3,Larian Studios,Larian Studios,NaN,736688,23974,0,"20,000,000 .. 50,000,000",8072,680,4912,310,5999,5999,0,54771
14,553850,HELLDIVERS 2,Arrowhead Game Studios,PlayStation Publishing LLC,NaN,775883,241752,0,"20,000,000 .. 50,000,000",5014,471,2385,196,3999,3999,0,53399

In [30]:
# Dropping unnecessary columns
steam_spy.drop(columns=["developer", "publisher", "score_rank", "userscore", "price", "initialprice", "discount"], inplace=True)
steam_spy.head()

,appid,name,positive,negative,owners,average_forever,average_2weeks,median_forever,median_2weeks,ccu
0,730,Counter-Strike: Global Offensive,7642084,1173003,"100,000,000 .. 200,000,000",33313,707,6299,329,1013936
2,578080,PUBG: BATTLEGROUNDS,1520457,1037487,"100,000,000 .. 200,000,000",24163,731,6086,336,314682
25,252490,Rust,1071135,156649,"20,000,000 .. 50,000,000",22059,1295,2988,694,143870
1,1172470,Apex Legends,668053,326926,"100,000,000 .. 200,000,000",10807,509,907,223,124262
19,431960,Wallpaper Engine,876898,17560,"20,000,000 .. 50,000,000",4777,140,1012,11,91184

In [31]:
# Replacing owners column with categories
# Create a mapping for cleaner category labels
owners_mapping = {
    '5,000,000 .. 10,000,000': '5M-10M',
    '10,000,000 .. 20,000,000': '10M-20M',
    '20,000,000 .. 50,000,000': '20M-50M',
    '50,000,000 .. 100,000,000': '50M-100M',
    '100,000,000 .. 200,000,000': '100M-200M'
}

# Add potential categories for lower and higher counts that might come up later
# Lower: '0 .. 5,000,000': '0-5M'
# Higher: '200,000,000 .. ': '200M+'

steam_spy['categories'] = steam_spy['owners'].map(owners_mapping)
steam_spy.drop(columns=['owners'], inplace=True)
steam_spy.head()

,appid,name,positive,negative,average_forever,average_2weeks,median_forever,median_2weeks,ccu,categories
0,730,Counter-Strike: Global Offensive,7642084,1173003,33313,707,6299,329,1013936,100M-200M
2,578080,PUBG: BATTLEGROUNDS,1520457,1037487,24163,731,6086,336,314682,100M-200M
25,252490,Rust,1071135,156649,22059,1295,2988,694,143870,20M-50M
1,1172470,Apex Legends,668053,326926,10807,509,907,223,124262,100M-200M
19,431960,Wallpaper Engine,876898,17560,4777,140,1012,11,91184,20M-50M

In [32]:
# Check for any missing fields
steam_spy.isna().sum()

appid              0
name               0
positive           0
negative           0
average_forever    0
average_2weeks     0
median_forever     0
median_2weeks      0
ccu                0
categories         0
dtype: int64

In [38]:
# Check column data types
steam_spy.dtypes

appid                 int64
name                 object
positive              int64
negative              int64
average_forever       int64
average_2weeks        int64
median_forever        int64
median_2weeks         int64
ccu                   int64
categories         category
dtype: object

In [43]:
# Converting name to string type
steam_spy['name'] = steam_spy['name'].astype('string')
steam_spy.dtypes
# Converting categories to categorical type
steam_spy['categories'] = steam_spy['categories'].astype('category')
steam_spy.dtypes

appid                       int64
name               string[python]
positive                    int64
negative                    int64
average_forever             int64
average_2weeks              int64
median_forever              int64
median_2weeks               int64
ccu                         int64
categories               category
dtype: object

In [44]:
# Adding ingestion date column based on filename
import re
m = re.search(r"(\d{4}-\d{2}-\d{2})", fname)
if m:
    steam_spy["ingestion_date"] = pd.to_datetime(m.group(1))

steam_spy.head()

,appid,name,positive,negative,average_forever,average_2weeks,median_forever,median_2weeks,ccu,categories,ingestion_date
0,730,Counter-Strike: Global Offensive,7642084,1173003,33313,707,6299,329,1013936,100M-200M,2026-03-18
2,578080,PUBG: BATTLEGROUNDS,1520457,1037487,24163,731,6086,336,314682,100M-200M,2026-03-18
25,252490,Rust,1071135,156649,22059,1295,2988,694,143870,20M-50M,2026-03-18
1,1172470,Apex Legends,668053,326926,10807,509,907,223,124262,100M-200M,2026-03-18
19,431960,Wallpaper Engine,876898,17560,4777,140,1012,11,91184,20M-50M,2026-03-18